name: hieronymus
services:
  db:
    cpu_shares: 90
    command: []
    container_name: db
    deploy:
      resources:
        limits:
          memory: 7811M
    environment:
      - POSTGRES_PASSWORD=ogochan
      - POSTGRES_USER=ogochan
    hostname: db
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ogochan -d ogochan
      timeout: 5s
      interval: 5s
      retries: 5
    image: postgres:15
    ports:
      - target: 5432
        published: "5432"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /var/lib/postgresql/data
    devices: []
    cap_add: []
    networks:
      - hieronymus
    privileged: false
  web:
    cpu_shares: 90
    command: []
    container_name: web
    depends_on:
      db:
        condition: service_healthy
        required: true
    deploy:
      resources:
        limits:
          memory: 7811M
    environment:
      - HOME=/app/$AppID
      - NODE_ENV=production
    hostname: web
    image: ghcr.io/waspcojp/hieronymus/hieronymus-web@sha256:2a0603b6c2a9de67334c816803cf718242b6cea0737f1f64e81005feaafdbafc
    init: true
    ports:
      - target: 3010
        published: "3010"
        protocol: tcp
    restart: always
    working_dir: /app/hieronymus
    volumes: []
    devices: []
    cap_add: []
    networks:
      - hieronymus
    privileged: false
networks:
  hieronymus:
    name: hieronymus
x-casaos:
  architectures:
    - amd64
    - arm64
  main: web
  author: BeesNestLLC
  category: 会計
  description:
    ja_jp: |
      Hieronymusは零細企業用のオープンソースERPシステムです。
    en_us: |
      Hieronymus is an open source ERP system for small businesses.
  developer: BeesNestLLC
  icon: "https://cdn.jsdelivr.net/gh/mayumigit/hieronymus@setup_casaos_appstore/public/icon-192x192.png"
  index: /
  tagline:
    ja_jp: Hieronymusは零細企業用のオープンソースERPシステムです。
    en_us: Hieronymus is an open source ERP system for small businesses.
  port_map: "3010"
  scheme: http
  title:
    en_us: Hieronymus
    ja_jp: Hieronymus
